---
- name: set MariaDB on yum repository
  template: src=mariadb.repo dest=/etc/yum.repos.d/mariadb.repo owner=root group=root mode=0644

- name: install MariaDB
  yum: name={{item}} state=present
  with_items:
    - MariaDB-server
    - MariaDB-client
    - MySQL-python

- name: enable service
  service: name=mysql state=started enabled=yes

- name: set root password
  mysql_user:
    name: root
    host: localhost
    password: "{{mysql_root_password}}"

- name: put .my.cnf
  template: src=.my.cnf dest=/root/.my.cnf owner=root mode=0600

