---
- name: copy /etc/hbase/conf.dist to /etc/hbase/conf.mycluster
  command: cp -R -p /etc/hbase/conf.dist /etc/hbase/conf.mycluster creates=/etc/hbase/conf.mycluster

- name: run update-alternatives to install hbase configuration
  command: update-alternatives --install /etc/hbase/conf hbase-conf /etc/hbase/conf.mycluster 50

- name: run update-alternatives to set hbase configuration
  command: update-alternatives --set hbase-conf /etc/hbase/conf.mycluster

- name: configure HBase in /etc/hbase/conf.mycluster
  template: src={{ item }}.j2 dest=/etc/hbase/conf.mycluster/{{ item }} owner=root group=root mode=0644
  with_items:
    - hbase-env.sh
    - hbase-policy.xml
    - hbase-site.xml
    - regionservers
  notify:
    - restart hbase-master
    - restart hbase-regionserver

